CREATE IF NOT EXISTS TABLE Continents (
    id PRIMARY KEY,
    it_name VARCHAR(20),
    en_name VARCHAR(20)
);

CREATE IF NOT EXISTS TABLE Countries (
    id PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    real_name VARCHAR(50) NOT NULL, --- name in the local language of the nation ---
    it_name VARCHAR(50) DEFAULT NULL,
    en_name VARCHAR(50) DEFAULT NULL,
    iso_alpha_3 CHAR(3) UNIQUE NOT NULL,
    fk_continent_id SMALLINT REFERENCES Continents
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE IF NOT EXISTS TABLE Cities (
    id PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    real_name VARCHAR(50) NOT NULL, --- name in the local language of the nation ---
    it_name VARCHAR(50) DEFAULT NULL,
    en_name VARCHAR(50) DEFAULT NULL,
    rating SMALLINT DEFAULT NULL, --- 0 to 5 rating ---
    fk_country_id INTEGER PRIMARY KEY REFERENCES Countries
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE IF NOT EXISTS TABLE Languages (
    id PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    abbreviation CHAR(2) NOT NULL
);

CREATE IF NOT EXISTS TABLE Users (
    firebase_id INTEGER PRIMARY KEY, --- The user id generated by firebase on CREATE IF NOT EXISTS ---
    fk_language_id INTEGER REFERENCES Languages
        ON DELETE SET 0 --- If the user deletes his account, the language is set to 0 (= English) ---
        ON UPDATE CASCADE
);

CREATE IF NOT EXISTS TABLE Monuments (
    id PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    real_name VARCHAR(50) NOT NULL, --- name in the local language of the nation ---
    it_name VARCHAR(50) DEFAULT NULL,
    en_name VARCHAR(50) DEFAULT NULL,
    coordinates GEOGRAPHY(POINT), --- Geography type from postgis ---
    it_description TEXT DEFAULT NULL,
    en_description TEXT DEFAULT NULL,
    fk_city_id INTEGER REFERENCES Cities
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE IF NOT EXISTS TABLE Visits ( 
    id PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    rating SMALLINT NOT NULL, --- 0 to 5 rating ---
    private_description TEXT DEFAULT NULL,
    date_time TIMESTAMP WITH TIME ZONE NOT NULL,
    fk_user_id INTEGER REFERENCES Users
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    fk_monument_id INTEGER REFERENCES Monuments
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE IF NOT EXISTS TABLE Types_of_Monuments (
    id PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    real_name VARCHAR(50) NOT NULL, --- name in the local language of the nation ---
    it_name VARCHAR(50) DEFAULT NULL,
    en_name VARCHAR(50) DEFAULT NULL
    it_description TEXT DEFAULT NULL,
    en_description TEXT DEFAULT NULL
    period_start DATE NOT NULL,
    period_end DATE DEFAULT NULL
);

CREATE IF NOT EXISTS TABLE Monuments_Types (
    fk_monument_id INTEGER REFERENCES Monuments
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    fk_type_id INTEGER REFERENCES Types_of_Monuments
        ON DELETE CASCADE
        ON UPDATE CASCADE
    PRIMARY KEY (fk_monument_id, fk_type_id)
);